### PR TITLE
feat: add [giscus](https://giscus.app) comment

### PR DESCRIPTION
**Pull request by DejavuMoe**

### CODE REVIEW

**Comment by Mivinci** [comment]
You can't just add the giscus template or its entire configuration into Minima for the reasons below:

1. When switching to the dark/light mode, giscus needs to be notified and changes as well.
2. Users, as lazy as they are, need us to make some simple and usable presets of any plugin's configuration.

So I'm closing this PR.

**Comment by qaqland** [comment]
So...
Is there a simpler way to add `<script>` or `<style>` into my page without editing the minima theme? Maybe I can do the configuration edit straightly in template html file.
祝好

**Comment by Mivinci** [comment]
应该是没有的，你要加 giscus 吗，我打算加但还没时间弄。

**Comment by qaqland** [comment]
我去看看文档，想想弄怎么简单一点

**Pull request closed without merging**
